version: '3.9'
services:
  postgresql:
    image: postgres:12
    container_name: bitbucket-postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bitbucket
      - POSTGRES_USER=bitbucket
      - POSTGRES_PASSWORD=bitbucket
    volumes:
      - /data/postgresql:/var/lib/postgresql/data
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    networks:
      - bitbucket-net

  bitbucket:
    image: atlassian/bitbucket:8.19.2
    container_name: bitbucket
    ports:
      - "7990:7990"    # Web UI
      - "7999:7999"    # Git SSH access
    depends_on:
      - postgresql
    volumes:
      - /data/bitbucket:/var/atlassian/application-data/bitbucket
    environment:
      - JDBC_DRIVER=org.postgresql.Driver
      - JDBC_URL=jdbc:postgresql://postgresql:5432/bitbucket
      - JDBC_USER=bitbucket
      - JDBC_PASSWORD=bitbucket
      - JVM_MINIMUM_MEMORY=1024m
      - JVM_MAXIMUM_MEMORY=4096m
    restart: always
    deploy:
      resources:
        limits:
          memory: 4g
    networks:
      - bitbucket-net

networks:
  bitbucket-net:
    driver: bridge
