bitbucket_image: atlassian/bitbucket:8.19.2
bitbucket_container_name: bitbucket
bitbucket_port: 8081
bitbucket_data_dir: /data/bitbucket
postgresql_data_dir: /data/postgresql

#
db_user: bitbucket
db_password: bitbucket
db_name: bitbucket
db_host: postgresql
db_port: 5432
#
postgres_image: postgres:12
